### ISSUE TITLE
missing LICENSE file

### ISSUE THREAD

**Issue by jasonjckn** [esuomi/muotti#20]
Hi, 
Thanks for putting out this neat little library, 

can you please put this under a license, this is necessary for corporate use, preferably MIT.

**Comment by jasonjckn** [comment]
Just noticed project.clj has a license, but maybe it was auto-generated for you?
If you can, my request is to remove the GPL from project.clj, and add a MIT 'LICENSE' file.

**Comment by esuomi** [comment]
Hi and thanks for the report! I suspect I've just forgotten to add that file into the repository, I'm usually the one to complain about missing licenses. I agree on the GPL, although normally I've been using EPL to reflect Clojure's own license, MIT and ASF2.0 are the ones I generally prefer.
